FROM scratch

ARG TARGETPLATFORM

EXPOSE 10000

COPY $TARGETPLATFORM/sablier /bin/sablier
COPY docker/sablier.yaml /etc/sablier/sablier.yaml

ENTRYPOINT [ "sablier" ]
CMD [ "--configFile=/etc/sablier/sablier.yaml", "start" ]
