sonar.organization=sablierapp
sonar.projectKey=sablierapp_sablier
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go,cmd/**,**/apitest/**,**/providertest/**,**/storetest/**
sonar.exclusions=**/apitest/**,**/providertest/**,**/storetest/**,pkg/theme/embedded/**,examples/**,docs/**,**/*.md,pkg/config/**
sonar.go.coverage.reportPaths=coverage.out

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=go:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.go