sonar.organization=sablierapp
sonar.projectKey=sablierapp_sablier
sonar.coverage.exclusions=**/*_test.go,**/apitest/**,**/providertest/**,**/storetest/**
sonar.exclusions=**/*_test.go,**/apitest/**,**/providertest/**,**/storetest/**
sonar.go.coverage.reportPaths=coverage.txt