sonar.organization=sablierapp
sonar.projectKey=sablierapp_sablier
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go,**/apitest/**,**/providertest/**,**/storetest/**
sonar.exclusions=**/*_test.go,**/apitest/**,**/providertest/**,**/storetest/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.ico,**/*.svg
sonar.go.coverage.reportPaths=coverage.out