// Command labelsgen generates the Label reference documentation page from the
// structured doc comments on the label constants in pkg/sablier/labels.go, so
// the documented labels never drift from the code that parses them. Run via
// `go generate ./...` / `make labels-docs`.
//
// The page mirrors the CLI reference (cmd/docgen): a shared "Applying labels"
// section shows how to attach a label on each provider, an index table lists
// every label, and each label gets a section with metadata badges.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/sablierapp/sablier/internal/docsmd"
	"github.com/sablierapp/sablier/internal/docsver"
	"github.com/sablierapp/sablier/internal/labeldoc"
)

func main() {
	src := flag.String("src", "pkg/sablier/labels.go", "path to the labels source file")
	out := flag.String("out", "", "output file path (writes to stdout if empty)")
	flag.Parse()

	labels, err := labeldoc.Parse(*src)
	if err != nil {
		log.Fatalf("parse %s: %v", *src, err)
	}
	if len(labels) == 0 {
		log.Fatalf("no labels found in %s", *src)
	}

	var b strings.Builder
	writeFrontMatter(&b)
	writeIntro(&b)
	writeApplying(&b)
	writeIndex(&b, labels)
	for _, l := range labels {
		writeLabel(&b, l)
	}

	data := []byte(b.String())
	if *out == "" {
		_, _ = os.Stdout.Write(data)
		return
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	log.Printf("label reference written to %s", *out)
}

func writeFrontMatter(b *strings.Builder) {
	b.WriteString("---\n")
	b.WriteString("title: Label reference\n")
	b.WriteString("weight: 312\n")
	b.WriteString("---\n\n")
	b.WriteString("<!-- Code generated by cmd/labelsgen (\"go generate ./...\"); DO NOT EDIT. -->\n")
	b.WriteString("<!-- Regenerate with `make labels-docs` after changing pkg/sablier/labels.go. -->\n\n")
}

func writeIntro(b *strings.Builder) {
	b.WriteString("Sablier discovers and manages your workloads through these `sablier.*` labels. ")
	b.WriteString("Each label is documented below with its type, the version it was introduced in, and any provider-specific behaviour. ")
	b.WriteString("See the [compatibility matrix](/reference/compatibility/) for an at-a-glance provider grid.\n\n")
}

// writeApplying is the labels analog of the CLI reference's "Setting an option":
// it shows, once, how the same label is attached on each provider.
func writeApplying(b *strings.Builder) {
	b.WriteString("## Applying labels {#applying-labels}\n\n")
	b.WriteString("Attach the labels to the workload Sablier should manage. The mechanism differs per provider; the per-label notes below call out any provider-specific form.\n\n")
	b.WriteString("{{< tabs >}}\n")

	b.WriteString("{{< tab name=\"Docker\" >}}\n")
	b.WriteString("```yaml\n")
	b.WriteString("services:\n  whoami:\n    image: containous/whoami\n    labels:\n      sablier.enable: \"true\"\n      sablier.group: \"my-group\"\n")
	b.WriteString("```\n")
	b.WriteString("{{< /tab >}}\n")

	b.WriteString("{{< tab name=\"Docker Swarm\" >}}\n")
	b.WriteString("```yaml\n")
	b.WriteString("services:\n  whoami:\n    image: containous/whoami\n    deploy:\n      labels:\n        sablier.enable: \"true\"\n        sablier.group: \"my-group\"\n")
	b.WriteString("```\n")
	b.WriteString("{{< /tab >}}\n")

	b.WriteString("{{< tab name=\"Kubernetes\" >}}\n")
	b.WriteString("```yaml\n")
	b.WriteString("metadata:\n  labels:\n    sablier.enable: \"true\"      # discovery uses a label selector\n  annotations:\n    sablier.group: \"my-group\"   # all other settings are annotations\n")
	b.WriteString("```\n")
	b.WriteString("{{< /tab >}}\n")

	b.WriteString("{{< tab name=\"Proxmox LXC\" >}}\n")
	b.WriteString("```bash\n")
	b.WriteString("# Proxmox has no key/value labels, so Sablier reads container tags:\n")
	b.WriteString("sablier                 # enables management (sablier.enable=true)\n")
	b.WriteString("sablier-group-my-group  # one tag per group\n")
	b.WriteString("```\n")
	b.WriteString("{{< /tab >}}\n")

	b.WriteString("{{< /tabs >}}\n\n")
}

func writeIndex(b *strings.Builder, labels []labeldoc.Label) {
	b.WriteString("## Labels {#labels}\n\n")
	b.WriteString("| Label | Description |\n")
	b.WriteString("|-------|-------------|\n")
	for _, l := range labels {
		fmt.Fprintf(b, "| [`%s`](#%s) | %s |\n", l.Name, anchor(l.Name), docsmd.EscapePipe(docsmd.FirstSentence(l.Description)))
	}
	b.WriteString("\n")
}

func writeLabel(b *strings.Builder, l labeldoc.Label) {
	fmt.Fprintf(b, "### `%s` {#%s}\n\n", l.Name, anchor(l.Name))
	if l.Description != "" {
		fmt.Fprintf(b, "%s\n\n", l.Description)
	}

	// Metadata badges: type, default (when set), required, and introduction version.
	var badges []string
	if l.Type != "" {
		badges = append(badges, fmt.Sprintf("{{< badge %q >}}", l.Type))
	}
	if l.Default != "" {
		badges = append(badges, fmt.Sprintf("{{< badge content=%q >}}", "Default: "+l.Default))
	}
	if l.Required {
		badges = append(badges, "{{< badge content=\"Required\" >}}")
	}
	if bs := docsver.SinceBadge(l.Since); bs != "" {
		badges = append(badges, bs)
	}
	if len(badges) > 0 {
		fmt.Fprintf(b, "%s\n\n", strings.Join(badges, " "))
	}

	if l.Example != "" {
		fmt.Fprintf(b, "Example: `%s`\n\n", l.Example)
	}
	if l.Providers != "" {
		fmt.Fprintf(b, "{{< callout type=\"info\" >}}\n%s\n{{< /callout >}}\n\n", l.Providers)
	}
	if l.Feature != "" {
		fmt.Fprintf(b, "[Learn more](%s)\n\n", l.Feature)
	}
}

// anchor returns the stable heading id for a label (set via a `{#id}` attribute).
func anchor(name string) string {
	return "label-" + strings.ReplaceAll(name, ".", "-")
}
