// Command labelsgen generates the Label reference documentation page from the
// structured doc comments on the label constants in pkg/sablier/labels.go, so
// the documented labels never drift from the code that parses them. Run via
// `go generate ./...` / `make labels-docs`.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/sablierapp/sablier/internal/labeldoc"
)

func main() {
	src := flag.String("src", "pkg/sablier/labels.go", "path to the labels source file")
	out := flag.String("out", "", "output file path (writes to stdout if empty)")
	flag.Parse()

	labels, err := labeldoc.Parse(*src)
	if err != nil {
		log.Fatalf("parse %s: %v", *src, err)
	}
	if len(labels) == 0 {
		log.Fatalf("no labels found in %s", *src)
	}

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: Label reference\n")
	b.WriteString("weight: 143\n")
	b.WriteString("---\n\n")
	b.WriteString("<!-- Code generated by cmd/labelsgen (\"go generate ./...\"); DO NOT EDIT. -->\n")
	b.WriteString("<!-- Regenerate with `make labels-docs` after changing pkg/sablier/labels.go. -->\n\n")
	b.WriteString("Sablier discovers and manages your workloads through these `sablier.*` labels. ")
	b.WriteString("Provider-specific setup (Kubernetes annotations, Proxmox tags, Docker-only features) is noted per label and covered in depth on the linked feature pages. ")
	b.WriteString("See the [compatibility matrix](/compatibility/) for an at-a-glance provider grid.\n\n")

	for _, l := range labels {
		fmt.Fprintf(&b, "## `%s`\n\n", l.Name)
		if l.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", l.Description)
		}
		writeItem(&b, "Type", l.Type)
		writeItem(&b, "Default", l.Default)
		if l.Example != "" {
			fmt.Fprintf(&b, "- **Example:** `%s`\n", l.Example)
		}
		if l.Required {
			b.WriteString("- **Required:** yes\n")
		}
		if s := sinceMarkdown(l.Since); s != "" {
			fmt.Fprintf(&b, "- **Since:** %s\n", s)
		}
		writeItem(&b, "Providers", l.Providers)
		if l.Feature != "" {
			fmt.Fprintf(&b, "- **Learn more:** [feature page](%s)\n", l.Feature)
		}
		b.WriteString("\n")
	}

	data := []byte(b.String())
	if *out == "" {
		_, _ = os.Stdout.Write(data)
		return
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	log.Printf("label reference written to %s", *out)
}

func writeItem(b *strings.Builder, label, value string) {
	if value == "" {
		return
	}
	fmt.Fprintf(b, "- **%s:** %s\n", label, value)
}

// sinceMarkdown renders a "since" version: a link to its GitHub release for a
// tagged version, or the raw text (e.g. "unreleased") otherwise.
func sinceMarkdown(v string) string {
	if v == "" {
		return ""
	}
	if strings.HasPrefix(v, "v") {
		return fmt.Sprintf("[%s](https://github.com/sablierapp/sablier/releases/tag/%s)", v, v)
	}
	return v
}
