// Command docgen generates the CLI / configuration reference documentation page
// from the cobra command definitions and writes it to the given output file. It
// is intended to be run via `go generate ./...` / `make cli-docs`, so the
// documented flags, defaults, environment variables and "since" versions never
// drift from the code in pkg/sabliercmd.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/sablierapp/sablier/pkg/sabliercmd"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	out := flag.String("out", "", "output file path (writes to stdout if empty)")
	flag.Parse()

	root := sabliercmd.NewRootCommand()

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: CLI reference\n")
	b.WriteString("weight: 145\n")
	b.WriteString("tabs:\n")
	b.WriteString("  sync: true\n")
	b.WriteString("---\n\n")
	b.WriteString("<!-- Code generated by cmd/docgen (\"go generate ./...\"); DO NOT EDIT. -->\n")
	b.WriteString("<!-- Regenerate with `make cli-docs` after changing flags in pkg/sabliercmd. -->\n\n")
	b.WriteString("Every option can be set three ways, in increasing precedence: ")
	b.WriteString("**configuration file -> environment variable -> command-line flag**. ")
	b.WriteString("See [Configuration](/configuration/) for the file search order and precedence rules. ")
	b.WriteString("Each option below shows all three forms; pick a tab and it stays selected across the page.\n\n")

	writeValueTypes(&b)

	// One section per subcommand (start, health, version, ...), sorted for a
	// stable diff so `make check-cli-docs` is reliable.
	cmds := root.Commands()
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name() < cmds[j].Name() })
	for _, c := range cmds {
		if !c.IsAvailableCommand() || c.Name() == "help" {
			continue
		}
		writeCommand(&b, c)
	}

	// Persistent flags shared by every command.
	if root.PersistentFlags().HasFlags() {
		b.WriteString("## Global flags\n\n")
		b.WriteString("Available on every command.\n\n")
		writeFlags(&b, root.PersistentFlags())
	}

	data := []byte(b.String())
	if *out == "" {
		_, _ = os.Stdout.Write(data)
		return
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	log.Printf("CLI reference written to %s", *out)
}

func writeValueTypes(b *strings.Builder) {
	b.WriteString("## Value types\n\n")
	b.WriteString("The **Type** of each option below links here.\n\n")
	b.WriteString("### string\n\nAny text value.\n\n")
	b.WriteString("### integer\n\nA whole number.\n\n")
	b.WriteString("### number\n\nA decimal number.\n\n")
	b.WriteString("### boolean\n\n`true` or `false`.\n\n")
	b.WriteString("### duration\n\nA Go duration string, e.g. `5m`, `1m30s`, `20s`, `500ms`.\n\n")
}

func writeCommand(b *strings.Builder, c *cobra.Command) {
	fmt.Fprintf(b, "## `%s`\n\n", c.CommandPath())
	if c.Short != "" {
		fmt.Fprintf(b, "%s\n\n", c.Short)
	}
	flags := c.LocalFlags()
	if !flags.HasFlags() {
		b.WriteString("_This command takes no flags of its own._\n\n")
		return
	}
	writeFlags(b, flags)
}

// writeFlags renders one small section per flag: a consolidated meta line, then
// the config-file / environment-variable / command-line forms as copyable tabs.
func writeFlags(b *strings.Builder, fs *pflag.FlagSet) {
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		fmt.Fprintf(b, "### `--%s`\n\n", f.Name)
		if usage := strings.TrimSpace(f.Usage); usage != "" {
			fmt.Fprintf(b, "%s\n\n", usage)
		}

		typeLabel, typeAnchor := valueType(f.Value.Type())
		meta := []string{}
		if typeAnchor != "" {
			meta = append(meta, fmt.Sprintf("**Type:** [%s](#%s)", typeLabel, typeAnchor))
		} else {
			meta = append(meta, fmt.Sprintf("**Type:** %s", typeLabel))
		}
		if f.DefValue != "" {
			meta = append(meta, fmt.Sprintf("**Default:** `%s`", f.DefValue))
		}
		if s := sinceMarkdown(sabliercmd.SinceForFlag(f.Name)); s != "" {
			meta = append(meta, fmt.Sprintf("**Since:** %s", s))
		}
		fmt.Fprintf(b, "%s\n\n", strings.Join(meta, " &middot; "))

		val := f.DefValue
		fmt.Fprintf(b, "{{< tabs >}}\n")
		fmt.Fprintf(b, "{{< tab name=\"Config file\" >}}\n\n```yaml\n%s\n```\n\n{{< /tab >}}\n", yamlExample(f.Name, val))
		fmt.Fprintf(b, "{{< tab name=\"Environment variable\" >}}\n\n```bash\n%s=%s\n```\n\n{{< /tab >}}\n", envVar(f.Name), val)
		fmt.Fprintf(b, "{{< tab name=\"Command-line flag\" >}}\n\n```bash\n--%s=%s\n```\n\n{{< /tab >}}\n", f.Name, val)
		fmt.Fprintf(b, "{{< /tabs >}}\n\n")
	})
}

// valueType maps a pflag value type to a display label and the anchor of its
// entry in the "Value types" section ("" for types without an entry).
func valueType(t string) (label, anchor string) {
	switch t {
	case "string":
		return "string", "string"
	case "int", "int32", "int64":
		return "integer", "integer"
	case "float", "float32", "float64":
		return "number", "number"
	case "bool":
		return "boolean", "boolean"
	case "duration":
		return "duration", "duration"
	default:
		return t, ""
	}
}

// yamlExample renders the nested YAML form of a dotted flag name with its value.
func yamlExample(name, value string) string {
	parts := strings.Split(name, ".")
	if value == "" {
		value = `""`
	}
	var b strings.Builder
	for i, p := range parts {
		indent := strings.Repeat("  ", i)
		if i == len(parts)-1 {
			fmt.Fprintf(&b, "%s%s: %s", indent, p, value)
		} else {
			fmt.Fprintf(&b, "%s%s:\n", indent, p)
		}
	}
	return b.String()
}

// sinceMarkdown renders a "since" version: a link to its GitHub release for a
// tagged version, or the raw text (e.g. "unreleased") otherwise.
func sinceMarkdown(v string) string {
	if v == "" {
		return ""
	}
	if strings.HasPrefix(v, "v") {
		return fmt.Sprintf("[%s](https://github.com/sablierapp/sablier/releases/tag/%s)", v, v)
	}
	return v
}

// envVar mirrors the binding in pkg/sabliercmd.bindFlags: the flag name is
// upper-cased with "-" and "." replaced by "_", then prefixed with "SABLIER_".
func envVar(name string) string {
	s := strings.ToUpper(name)
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	return "SABLIER_" + s
}
