// Command docgen generates the CLI / configuration reference documentation page
// from the cobra command definitions and writes it to the given output file. It
// is intended to be run via `go generate ./...` / `make cli-docs`, so the
// documented flags, defaults, environment variables and "since" versions never
// drift from the code in pkg/sabliercmd.
//
// The page uses "Layout F": each configuration category has a scannable index
// table linking to a per-option section that shows the type, introduction
// version and all three ways to set the option (file, environment, flag).
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/sablierapp/sablier/internal/configdoc"
	"github.com/sablierapp/sablier/internal/docsver"
	"github.com/sablierapp/sablier/pkg/config"
	"github.com/sablierapp/sablier/pkg/sabliercmd"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// sinceByFlag maps a flag name to the version it was introduced in, parsed from
// the "Since:" doc comments on the pkg/config struct fields. Populated in main.
var sinceByFlag map[string]string

// option is a single flag flattened with everything the page needs to render it.
type option struct {
	name    string   // flag name, e.g. "server.port" or "url"
	usage   string   // description
	typ     string   // display type label (string, integer, ...)
	def     string   // default value ("" when none)
	since   string   // introduction version ("" when unknown)
	enum    []string // accepted values, or nil
	envimpl bool     // true when the option is bound to config file + environment
}

// categoryOrder is the fixed section order for the configuration options.
var categoryOrder = []string{"General", "Logging", "Provider", "Server", "Sessions", "Storage", "Strategy", "Tracing"}

// enumValues lists the accepted values for the options that take a fixed set,
// sourced from the code where possible so the list never drifts.
func enumValues() map[string][]string {
	return map[string][]string{
		"provider.name":            config.GetProviders(),
		"provider.docker.strategy": config.GetDockerStrategies(),
		"logging.level":            {"error", "warn", "info", "debug"},
		"tracing.exporter-type":    {"otlphttp", "stdout"},
	}
}

func main() {
	out := flag.String("out", "", "output file path (writes to stdout if empty)")
	configSrc := flag.String("config-src", "pkg/config", "path to the pkg/config source directory (read for \"Since:\" doc comments)")
	flag.Parse()

	var err error
	sinceByFlag, err = configdoc.SinceByFlag(*configSrc)
	if err != nil {
		log.Fatalf("parse config docs in %s: %v", *configSrc, err)
	}

	root := sabliercmd.NewRootCommand()

	var startCmd *cobra.Command
	for _, c := range root.Commands() {
		if c.Name() == "start" {
			startCmd = c
		}
	}

	// Collect the configuration options (persistent + start flags) grouped by
	// category, and keep the per-command flags for the Commands section.
	enums := enumValues()
	byCategory := map[string][]option{}
	collect := func(fs *pflag.FlagSet) {
		fs.VisitAll(func(f *pflag.Flag) {
			if f.Hidden {
				return
			}
			o := newOption(f, enums)
			cat := categoryOf(o.name)
			byCategory[cat] = append(byCategory[cat], o)
		})
	}
	collect(root.PersistentFlags())
	if startCmd != nil {
		collect(startCmd.LocalFlags())
	}
	for _, opts := range byCategory {
		sort.Slice(opts, func(i, j int) bool { return opts[i].name < opts[j].name })
	}

	var b strings.Builder
	writeFrontMatter(&b)
	writeIntro(&b)
	writeCommands(&b, root, startCmd, enums)
	writeSettingAnOption(&b)
	writeValueTypes(&b)

	for _, cat := range categoryOrder {
		opts := byCategory[cat]
		if len(opts) == 0 {
			continue
		}
		writeCategory(&b, cat, opts)
	}

	data := []byte(b.String())
	if *out == "" {
		_, _ = os.Stdout.Write(data)
		return
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	log.Printf("CLI reference written to %s", *out)
}

func newOption(f *pflag.Flag, enums map[string][]string) option {
	return option{
		name:    f.Name,
		usage:   strings.TrimSpace(f.Usage),
		typ:     typeLabel(f.Value.Type()),
		def:     f.DefValue,
		since:   sinceByFlag[f.Name],
		enum:    enums[f.Name],
		envimpl: strings.Contains(f.Name, "."), // dotted keys are config-file + env bound
	}
}

func writeFrontMatter(b *strings.Builder) {
	b.WriteString("---\n")
	b.WriteString("title: CLI reference\n")
	b.WriteString("weight: 310\n")
	b.WriteString("---\n\n")
	b.WriteString("<!-- Code generated by cmd/docgen (\"go generate ./...\"); DO NOT EDIT. -->\n")
	b.WriteString("<!-- Regenerate with `make cli-docs` after changing flags in pkg/sabliercmd. -->\n\n")
}

func writeIntro(b *strings.Builder) {
	b.WriteString("Sablier is configured through the `sablier` command. This page is generated from the command definitions, so it always matches the running binary. See [Configuration](/tutorials/configuration/) for the configuration file search order.\n\n")
}

func writeCommands(b *strings.Builder, root, startCmd *cobra.Command, enums map[string][]string) {
	b.WriteString("## Commands {#commands}\n\n")
	b.WriteString("Sablier exposes the following commands.\n\n")

	cmds := root.Commands()
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name() < cmds[j].Name() })
	for _, c := range cmds {
		if !c.IsAvailableCommand() || c.Name() == "help" {
			continue
		}
		fmt.Fprintf(b, "### `%s` {#command-%s}\n\n", c.CommandPath(), c.Name())
		if c.Short != "" {
			fmt.Fprintf(b, "%s\n\n", c.Short)
		}
		if c == startCmd {
			b.WriteString("Every option in the sections below configures this command.\n\n")
			continue
		}
		// Render the command's own flags (e.g. `health --url`) inline.
		c.LocalFlags().VisitAll(func(f *pflag.Flag) {
			if f.Hidden {
				return
			}
			writeOption(b, newOption(f, enums))
		})
	}
}

func writeSettingAnOption(b *strings.Builder) {
	b.WriteString("## Setting an option {#setting-an-option}\n\n")
	b.WriteString("Every configuration option can be set three ways, in increasing precedence: **configuration file, then environment variable, then command-line flag**.\n\n")
	b.WriteString("Option keys are dotted (for example `strategy.dynamic.default-theme`). In the configuration file, nest each segment. For the environment variable, upper-case the key, replace `.` and `-` with `_`, and add the `SABLIER_` prefix. As a flag, pass the key verbatim with a `--` prefix. Each option below shows all three forms.\n\n")
}

func writeValueTypes(b *strings.Builder) {
	b.WriteString("## Value types {#value-types}\n\n")
	b.WriteString("- **string**: any text value.\n")
	b.WriteString("- **integer**: a whole number.\n")
	b.WriteString("- **number**: a decimal number.\n")
	b.WriteString("- **boolean**: `true` or `false`.\n")
	b.WriteString("- **duration**: a Go duration string, e.g. `5m`, `1m30s`, `20s`, `500ms`.\n\n")
}

func writeCategory(b *strings.Builder, cat string, opts []option) {
	fmt.Fprintf(b, "## %s {#category-%s}\n\n", cat, strings.ToLower(cat))

	// Scannable index table for the category.
	b.WriteString("| Option | Description |\n")
	b.WriteString("|--------|-------------|\n")
	for _, o := range opts {
		fmt.Fprintf(b, "| [`--%s`](#%s) | %s |\n", o.name, optAnchor(o.name), escapePipe(firstSentence(o.usage)))
	}
	b.WriteString("\n")

	for _, o := range opts {
		writeOption(b, o)
	}
}

// writeOption renders one option: its heading, description, metadata badges,
// accepted values (when any) and the ways to set it.
func writeOption(b *strings.Builder, o option) {
	fmt.Fprintf(b, "### `--%s` {#%s}\n\n", o.name, optAnchor(o.name))
	if o.usage != "" {
		fmt.Fprintf(b, "%s\n\n", o.usage)
	}

	// Metadata badges: type, default (when set) and the version it was added in.
	badges := []string{fmt.Sprintf("{{< badge %q >}}", o.typ)}
	if o.def != "" {
		badges = append(badges, fmt.Sprintf("{{< badge content=%q >}}", "Default: "+o.def))
	}
	if bs := docsver.SinceBadge(o.since); bs != "" {
		badges = append(badges, bs)
	}
	fmt.Fprintf(b, "%s\n\n", strings.Join(badges, " "))

	if len(o.enum) > 0 {
		b.WriteString("Accepted values:\n\n")
		for _, v := range o.enum {
			fmt.Fprintf(b, "- `%s`\n", v)
		}
		b.WriteString("\n")
	}

	value := exampleValue(o.def, o.typ)
	if o.envimpl {
		fmt.Fprintf(b, "```yaml\n# sablier.yaml\n%s```\n\n", nestedYAML(o.name, value))
		fmt.Fprintf(b, "```bash\n# Environment variable\n%s=%s\n\n# Command-line flag\n--%s=%s\n```\n\n",
			envVar(o.name), value, o.name, value)
		return
	}
	// Flag-only options (e.g. --configFile, --url) have no file/env form.
	fmt.Fprintf(b, "```bash\n# Command-line flag\n--%s=%s\n```\n\n", o.name, value)
}

// categoryOf maps a flag name to its documentation category via the first key segment.
func categoryOf(name string) string {
	seg := name
	if i := strings.Index(name, "."); i >= 0 {
		seg = name[:i]
	}
	switch seg {
	case "logging":
		return "Logging"
	case "provider":
		return "Provider"
	case "server":
		return "Server"
	case "sessions":
		return "Sessions"
	case "storage":
		return "Storage"
	case "strategy":
		return "Strategy"
	case "tracing":
		return "Tracing"
	default:
		return "General"
	}
}

// optAnchor returns the stable heading id for an option (set via a `{#id}` attribute).
func optAnchor(name string) string {
	// Lower-cased so the link matches the heading id Goldmark emits (it does not
	// preserve the mixed case of e.g. --configFile).
	return strings.ToLower("opt-" + strings.ReplaceAll(name, ".", "-"))
}

// nestedYAML expands a dotted key into an indented YAML block ending with the value.
func nestedYAML(name, value string) string {
	parts := strings.Split(name, ".")
	var b strings.Builder
	for i, p := range parts {
		indent := strings.Repeat("  ", i)
		if i == len(parts)-1 {
			fmt.Fprintf(&b, "%s%s: %s\n", indent, p, value)
		} else {
			fmt.Fprintf(&b, "%s%s:\n", indent, p)
		}
	}
	return b.String()
}

// exampleValue returns the default when set, otherwise a type placeholder.
func exampleValue(def, typeLabel string) string {
	if def != "" {
		return def
	}
	return "<" + typeLabel + ">"
}

// typeLabel maps a pflag value type to a friendly display label.
func typeLabel(t string) string {
	switch t {
	case "string":
		return "string"
	case "int", "int32", "int64":
		return "integer"
	case "float", "float32", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "duration":
		return "duration"
	default:
		return t
	}
}

// envVar mirrors the binding in pkg/sabliercmd.bindFlags: the flag name is
// upper-cased with "-" and "." replaced by "_", then prefixed with "SABLIER_".
func envVar(name string) string {
	s := strings.ToUpper(name)
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	return "SABLIER_" + s
}

// abbreviations are tokens whose trailing period does not end a sentence, so the
// index truncation must not stop on them.
var abbreviations = []string{"e.g", "i.e", "etc", "vs"}

// firstSentence returns the first sentence of s (up to a sentence-ending ". "),
// keeping the index table compact. Common abbreviations (e.g., i.e.) do not end
// a sentence.
func firstSentence(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	for i := 0; i+1 < len(s); i++ {
		if s[i] != '.' || s[i+1] != ' ' {
			continue
		}
		fields := strings.Fields(s[:i])
		last := ""
		if len(fields) > 0 {
			last = strings.TrimLeft(fields[len(fields)-1], "([\"'")
		}
		abbrev := false
		for _, a := range abbreviations {
			if strings.EqualFold(last, a) {
				abbrev = true
				break
			}
		}
		if !abbrev {
			return s[:i+1]
		}
	}
	return s
}

func escapePipe(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
