// Command metricsgen generates the Metrics reference page from the actual
// Prometheus collectors in pkg/metrics. It registers every collector on a
// registry, exercises the metric vectors so their label names are exposed, then
// gathers the registry and renders name/type/labels/help for each metric — so
// the documented metrics never drift from the code. Run via `go generate ./...`
// / `make metrics-docs`.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/sablierapp/sablier/pkg/metrics"
)

// Fake providers so the lazy collectors emit one sample each (exposing their
// label names on gather).
type fakeGroups struct{}

func (fakeGroups) Groups() map[string][]string { return map[string][]string{"group": {"instance"}} }

type fakeActive struct{}

func (fakeActive) SnapshotActiveInstances() map[string]struct{} {
	return map[string]struct{}{"instance": {}}
}

type fakeSessions struct{}

func (fakeSessions) SessionsSnapshot() []metrics.SessionEntry {
	return []metrics.SessionEntry{{Instance: "instance", Group: "group", ExpiresAt: time.Unix(0, 0)}}
}

func main() {
	out := flag.String("out", "", "output file path (writes to stdout if empty)")
	flag.Parse()

	rec := metrics.NewPromRecorder()
	reg := rec.Registry().(*prometheus.Registry)
	reg.MustRegister(metrics.NewGroupLockCollector(fakeGroups{}, fakeActive{}))
	reg.MustRegister(metrics.NewSessionExpiryCollector(fakeSessions{}))

	// Exercise each recorder vector so its label names appear on gather.
	rec.RecordSessionRequest("dynamic", "group")
	rec.RecordInstanceStartFailure("instance")
	rec.RecordInstanceStop("instance", "expired")
	rec.RecordInstanceStartEnd("instance", time.Second)
	rec.RecordReadyWaitBegin("instance")
	rec.RecordReadyWaitEnd("instance")
	// RecordInactiveInstance only records sablier_instance_active_seconds_total
	// when a non-zero active duration has elapsed; sleep so the sample (and thus
	// the metric's metadata) is emitted deterministically, even on coarse clocks.
	time.Sleep(2 * time.Millisecond)
	rec.RecordInactiveInstance("instance")

	fams, err := reg.Gather()
	if err != nil {
		log.Fatalf("gather: %v", err)
	}

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: Metrics\n")
	b.WriteString("weight: 86\n")
	b.WriteString("---\n\n")
	b.WriteString("<!-- Code generated by cmd/metricsgen (\"go generate ./...\"); DO NOT EDIT. -->\n")
	b.WriteString("<!-- Regenerate with `make metrics-docs` after changing pkg/metrics. -->\n\n")
	b.WriteString("Sablier can expose a Prometheus-compatible `/metrics` endpoint. Enable it with the `server.metrics.enabled` option (see the [CLI reference](/cli/)).\n\n")
	b.WriteString("When set to `true`, Sablier registers a `GET <base-path>/metrics` route on the same HTTP server that handles `/health` and `/api/...`. The route returns the Prometheus text exposition format and is served by `promhttp`. When set to `false` (the default), the route is not registered and any request to that path returns `404`.\n\n")

	b.WriteString("## Exposed metrics\n\n")
	b.WriteString("| Name | Type | Labels | Description |\n")
	b.WriteString("|------|------|--------|-------------|\n")
	for _, mf := range fams {
		name := mf.GetName()
		if !strings.HasPrefix(name, "sablier_") {
			continue
		}
		typ := strings.ToLower(mf.GetType().String())
		labels := "—"
		if len(mf.GetMetric()) > 0 {
			names := make([]string, 0, len(mf.GetMetric()[0].GetLabel()))
			for _, lp := range mf.GetMetric()[0].GetLabel() {
				names = append(names, lp.GetName())
			}
			sort.Strings(names)
			if len(names) > 0 {
				labels = "`" + strings.Join(names, "`, `") + "`"
			}
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", name, typ, labels, escape(mf.GetHelp()))
	}
	b.WriteString("| Go runtime + process collectors | (default) | (default) | Standard `go_*` and `process_*` metrics from the Prometheus Go client. |\n\n")

	b.WriteString("## Security note\n\n")
	b.WriteString("The endpoint exposes process internals, group and instance names, and counters. It is intended for trusted observability stacks. Restrict at the reverse proxy when Sablier is fronted on an untrusted network.\n")

	data := []byte(b.String())
	if *out == "" {
		_, _ = os.Stdout.Write(data)
		return
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	log.Printf("metrics reference written to %s", *out)
}

func escape(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}
