#!/usr/bin/env bash
#
# Multi-version documentation build for https://sablierapp.dev
#
# Layout produced under docs/public:
#   /            latest stable release (highest vX.Y tag that ships Hugo docs)
#   /next/       the main branch (upcoming, unreleased); install snippets point
#                at the moving sablierapp/sablier:next image
#   /vX.Y/       every released minor (latest patch), accumulating over time
#
# Versions are derived from git tags. release-please creates a vX.Y.Z tag for
# every release, so the set of published versions grows automatically — there is
# no hand-maintained list. Tags without Hugo docs (docs/hugo.yaml absent, i.e.
# everything before the Hugo docs rework) are skipped, so accumulation starts
# cleanly with the first Hugo-docs release.
#
# Until the first Hugo-docs release exists, main is served at the root
# (bootstrap) as the "next" version, so the site keeps working in the meantime.
#
# Env overrides: BASE_URL (default https://sablierapp.dev), HUGO_ARGS.
set -euo pipefail

BASE_URL="${BASE_URL:-https://sablierapp.dev}"
HUGO_ARGS="${HUGO_ARGS:---gc --minify}"

DOCS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$DOCS_DIR" rev-parse --show-toplevel)"
PUBLIC="$DOCS_DIR/public"

rm -rf "$PUBLIC"

# --- Discover buildable released minors: latest patch per vX.Y, Hugo docs only.
# FOUND guards against expanding an empty associative array, which errors under
# `set -u` (${#arr[@]} / ${!arr[@]} on an empty assoc array is "unbound").
declare -A MINOR_TAG
FOUND=0
while read -r tag; do
  [ -n "$tag" ] || continue
  # Skip tags that predate the Hugo docs (no docs/hugo.yaml at that ref).
  git -C "$REPO_ROOT" cat-file -e "${tag}:docs/hugo.yaml" 2>/dev/null || continue
  minor="${tag%.*}" # v1.15.3 -> v1.15
  prev="${MINOR_TAG[$minor]:-}"
  if [ -z "$prev" ] || [ "$(printf '%s\n%s\n' "$prev" "$tag" | sort -V | tail -1)" = "$tag" ]; then
    MINOR_TAG["$minor"]="$tag"
    FOUND=1
  fi
done < <(git -C "$REPO_ROOT" tag --list 'v[0-9]*.[0-9]*.[0-9]*' | grep -vE '-') # exclude pre-releases

# Minors, newest first.
MINORS=()
if [ "$FOUND" -eq 1 ]; then
  while read -r m; do MINORS+=("$m"); done < <(printf '%s\n' "${!MINOR_TAG[@]}" | sort -Vr)
fi
LATEST_MINOR="${MINORS[0]:-}"

# --- Write the version list + current label consumed by the switcher.
# Newest first: next, then every released minor.
write_versions() { # <data_dir> <current-label>
  local data_dir="$1" current="$2"
  mkdir -p "$data_dir"
  {
    echo "# Generated by docs/build.sh — do not edit by hand."
    echo "current: ${current}"
    echo "list:"
    echo "  - name: next"
    echo "    url: ${BASE_URL}/next/"
    for m in "${MINORS[@]}"; do
      echo "  - name: ${m}"
      echo "    url: ${BASE_URL}/${m}/"
    done
  } >"$data_dir/versions.yaml"
}

# --- Build one version.
# <source-docs-dir> <dest-subpath> <baseurl-suffix> <current-label> [version-override]
# When version-override is set (the "next"/main builds), it overrides
# params.version so {{< version >}} — and therefore the install snippets — point
# at the moving image tag (e.g. sablierapp/sablier:next) instead of the last
# released semver. Released builds omit it and keep their own hugo.yaml version.
build() {
  local src="$1" dest="$2" suffix="$3" current="$4" ver="${5:-}"
  write_versions "$src/data" "$current"
  echo ">> building '${current}' -> ${PUBLIC}${dest} (baseURL ${BASE_URL}${suffix})"
  (
    cd "$src"
    [ -n "$ver" ] && export HUGO_PARAMS_VERSION="$ver"
    # shellcheck disable=SC2086
    hugo $HUGO_ARGS --baseURL "${BASE_URL}${suffix}" --destination "${PUBLIC}${dest}"
  )
}

# Build a released tag into /<minor>/ via a throwaway detached worktree.
build_tag() { # <minor> <dest-subpath> <baseurl-suffix>
  local minor="$1" dest="$2" suffix="$3" tag="${MINOR_TAG[$1]}" wt
  wt="$(mktemp -d)"
  git -C "$REPO_ROOT" worktree add --quiet --detach "$wt" "$tag"
  build "$wt/docs" "$dest" "$suffix" "$minor"
  git -C "$REPO_ROOT" worktree remove --force "$wt"
}

if [ -z "$LATEST_MINOR" ]; then
  echo ">> No Hugo-docs release tags yet — serving main at the root (bootstrap)."
  build "$DOCS_DIR" "" "/" "next" "next"
else
  echo ">> Latest stable: ${LATEST_MINOR} (${MINOR_TAG[$LATEST_MINOR]})"
  # main -> /next/ (version pinned to the moving :next image)
  build "$DOCS_DIR" "/next" "/next/" "next" "next"
  # every released minor -> /vX.Y/
  for m in "${MINORS[@]}"; do
    build_tag "$m" "/$m" "/$m/"
  done
  # latest stable is also served at the root
  build_tag "$LATEST_MINOR" "" "/"
fi

echo ">> done: ${PUBLIC}"
